### ISSUE TITLE
Unexpected behavior when switching jobs

### ISSUE THREAD

**Issue by Nillinn** [NightmareXIV/DynamicBridge#2]
First off, thank you, i was really looking forward to a plugin like this one.

I found out that switching jobs does not revert character to its normal state, causing it to remain wearing the outfit and weapon from the former job.

Example: 
>You are a Ninja. You use a Dynamic Rule to wear a Glamourer swimsuit preset when the "Swimming" state is active. It triggers normally.
>You leave the body of water. The outfit goes back to default, as expected.
>You switch jobs, from Ninja to Machinist.
>You are now a Machinist wearing your default Ninja clothes and weapons.
Happens with every job in every Dynamic Rule.

Workaround: The only solution at the moment is going to Glamourer and pressing this button in the designs tab: "Revert Player Character to their game state."

I tried using this plugin's setting called "revert character before applying new rule" but it didn't do anything in this situation.

**Comment by Limiana** [comment]
Hello! Thank you for reporting the issue. The fix will be released in next version

**Comment by Limiana** [comment]
@Nillinn Please test `revert character before applying new rule` checkbox again, it should be fixed now. Currently I'm waiting for Glamourer update which should implement additional ipc methods and have this completely resolved without need in that option.

**Comment by Nillinn** [comment]
Glamours are still getting stuck in between job switching, including the weapon. Tested with the setting on and off.

**Comment by Limiana** [comment]
@Nillinn Please check if the new update fixes your issue

**Comment by Nillinn** [comment]
Thank you. The new glamourer integration works quite well
